### ISSUE TITLE
remove glfw dependency

### ISSUE THREAD

**Issue by CreatureDev** [vulkan-go/vulkan#4]

**Comment by xlab** [comment]
@CreatureDev 
Hi! Is this a suggestion or a question?

In order to remove support of GLFW, one should implement all 5 backends that GLFW covers for now: OS X, windows, linux-xcb, linux-wayland and linux-mir.

And instead 1 very popular, very lightweight dependency that is kept up-to-date, we will have 5 more dependencies with almost no guarantees nor support.

**Comment by CreatureDev** [comment]
It was a suggestion as vulkan programs do not need a window to function. People could choose to create a program that simply does compute or off-screen rendering, and the GLFW dependency does nothing but inflate their program.

**Comment by xlab** [comment]
@CreatureDev I understand your concern, note that for systems that really doesn't need a window, like Android and compute, there is no GLFW dependency.

The target is called "compute" and can be activated using building tag: `-tags compute`
https://github.com/vulkan-go/vulkan/blob/master/vulkan_compute.go

GLFW comes into the play only if you really need a window.

**Comment by CreatureDev** [comment]
Ah I didn't realize that was an option
Thanks

**Comment by jclc** [comment]
What if you use another library like SDL2 or SFML?
